title: "Diaries of a Modern Ninja"
description: "Nima's Diaries about Cybersecurity, Red Teaming, Tooling, Tutorials, and Personal Notes — Practical Guides, Walkthroughs, and Resources for Curious Minds."
author:
  name: "Nima"
  twitter: "cSh4rk"

url: "https://nima.ninja"
baseurl: ""

source: .
destination: ./_site
permalink: /:categories/:year/:title
paginate: 10
paginate_path: /page/:num/
timezone: America/New_York

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  
exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - copy-css.js
  
sass:
  style: compressed
  sourcemap: never
  
#google_analytics: [Your Google Analytics tracking ID]

# Custom variables
owner : "Nima"
year : "2025"

twitter:
  username: cSh4rk
  card: summary_large_image

# Contact
social:
  name: cSh4rk
  email: "nima@nima.ninja"
  email2: "csh4rk0x00@protonmail.com"
  github: "cSh4rk"
  githubname: "Shark"
  x: "cSh4rk"
  xname: "Shark"
  mastodon: "https://infosec.exchange/@cSh4rk"
  mastodonhandle: "@cSh4rk"
  mastodonname: "Shark"
  linkedin: 
  pgpkey: "CEE9A66A2F5C6187E4242B0425669795B037FEF2.asc"
  discorduser: "csh4rk"
  discordserver: "4btHxXWwgQ"
  discordservername: "Sharks"
  wickrme: "csh4rk"
  linktree: "cSh4rk"
  tally: "wgrO5K"
  whispa: "nima"
  tellonym: "__nima__"
  links:
    - https://twitter.com/cSh4rk
    - https://github.com/cSh4rk

badges:
  hackthebox: "768488"
  selfhost_hackthebox: true
  tryhackme: "nima"
  selfhost_tryhackme: true
# End of Contact
