=begin
# _plugins/clean_footnotes.rb
# This plugin automatically cleans footnotes HTML generated by kramdown
# - Removes role="doc-noteref" from <sup>
# - Removes role="doc-endnote" from <li>
# - Keeps links and numbers intact

Jekyll::Hooks.register :posts, :post_render do |post|
  # Only process HTML posts
  next unless post.output_ext == '.html'

  # Remove role="doc-noteref" from <sup>
  post.output.gsub!(/<sup([^>]*)\srole="doc-noteref"/, '<sup\1')

  # Remove role="doc-endnote" from <li>
  post.output.gsub!(/<li([^>]*)\srole="doc-endnote"/, '<li\1')

  # Remove role="doc-endnotes" from the wrapping div
  post.output.gsub!(/<div([^>]*)\srole="doc-endnotes"/, '<div\1')

  # Remove role="doc-backlink" from the reverse footnote arrows
  post.output.gsub!(/<a([^>]*)\srole="doc-backlink"/, '<a\1')
end
=end